const default_prices = {
    "ste" : {"initial_price" : 1.5, "crash_price" : 0.7, "min_price" : 0.4, "full_name":"Stella"},
    "bar" : {"initial_price" : 2.0, "crash_price" : 1.1, "min_price" : 1.0, "full_name":"Barbar"},
    "cho" : {"initial_price" : 2.0, "crash_price" : 1.1, "min_price" : 0.8, "full_name":"Chouffe"},
    "duv" : {"initial_price" : 1.5, "crash_price" : 0.8, "min_price" : 0.4, "full_name":"Duvel"},
    "trk" : {"initial_price" : 2.0, "crash_price" : 1.1, "min_price" : 0.9, "full_name":"Triple K"},
    "kwk" : {"initial_price" : 2.0, "crash_price" : 1.1, "full_name":"Kwak"},
    "gul" : {"initial_price" : 2.0, "crash_price" : 1.1, "full_name":"Gulden Draak"},
    "kaa" : {"initial_price" : 2.0, "crash_price" : 1.1, "full_name":"Kaastel Triple"},
    "hoe" : {"initial_price" : 1.8, "crash_price" : 0.2, "full_name":"Hoegaarden blanche"},
    "pel" : {"initial_price" : 1.5, "crash_price" : 0.2, "full_name":"Pelforth"},
    "cht" : {"initial_price" : 1.0, "crash_price" : 0.3, "full_name":"Chti"},
    "lef" : {"initial_price" : 1.0, "crash_price" : 0.3, "full_name":"Leffe"},
    "des" : {"initial_price" : 1.5, "crash_price" : 0.7, "full_name":"Despe"},
    "mor" : {"initial_price" : 1.0, "crash_price" : 0.3, "full_name":"Mordue"},
    "pec" : {"initial_price" : 1.5, "crash_price" : 1.1, "full_name":"Peche Mel"},
    "cor" : {"initial_price" : 2.0, "crash_price" : 0.7, "full_name":"Corona"},
    "pin" : {"initial_price" : 1.5, "crash_price" : 0.8, "full_name":"Pinte Sangria"},
    "Pbe" : {"initial_price" : 3, "crash_price" : 1.4, "full_name":"Bête (Pinte)"},
}
